# Conclusões e recomendações

Esse trabalho de mestrado teve como objetivo geral analisar a variabilidade de indicadores de acessibilidade por transporte público às oportunidades cumulativas de trabalho e educação com o uso de big data no contexto da avaliação de intervenções no sistema de transportes. Esse objetivo geral foi dividido em cinco objetivos específicos de pesquisa.

O primeiro objetivo disse respeito à consolidação e integração dos dados de transporte público de Fortaleza. No capítulo 3 foi mostrado que a integração das bases era falha: havia falta de correspondência entre bilhetagem, GPS e GTFS para diversas linhas e veículos. Isso ocasionou uma limitação que deveria ser reconhecida para a etapa do estabelecimento da metodologia. Por fim, dados de bilhetagem, GPS, GTFS e cadastro dos usuários foram prontos para o desenvolvimento do método que viria em seguida.

O segundo objetivo tratou do estabelecimento de uma método para a reconstrução de horários programados de transporte público para tendo em vista as hipóteses estabelecidas e as limitações encontradas nos dados consolidados e integrados. Esse objetivo foi atingido no primeiro tópico do capítulo 4, denominado de integração entre o GPS e GTFS, já olhando para as suas aplicações para a estimação da acessibilidade. 

O método apresentado para a reconstrução das viagens agendadas do GTFS a partir de dados arquivados de GPS permitiu fazer essa reconstrução quando não se tem os dados populacionais do rastreamento da frota. Primeiramente, foi necessário transformar os dados de GPS (registros a cada 30s de quase todos os veículos do transporte público) em uma tabela de horários de passagem em cada parada. Para isso, foram necessárias três etapas principais: a definição das viagens, a definição do sentido da viagem e a estimação do momento de passagem em cada parada.

Na primeira etapa, foi proposto um método que apresentava avanços em relação aos demais métodos encontrados na literatura, considerando o tempo total de viagem do veículo e o tempo que ele gastou com embarques/desembarques entre uma viagem e outra. Na segunda etapa, o método não foi diferente do que foi adotado na literatura. Na terceira, foi proposta uma interpolação linear na rede para a estimação do momento de passagem de cada veículo em cada parada programada, o que foi entendido como um avanço em relação aos método anteriores que só interpolam quando a parada não era estimada. A aplicação dessas três etapas permite então a criação de uma tabela de horários em cada parada para todos os veículos que puderem ser estimados.

Sabendo que essas tabelas de horários não representavam todas as linhas e veículos, foi então proposta uma agregação das mesmas. Para isso, todos os horários de passagem foram agregados para os trechos entre paradas e intervalos de 15 minutos mais próximos. Essa agregação, buscando avaliar o efeito da variação do tempo de viagem do sistema na acessibilidade, foi feita para duas medidas: a mediana dos tempos de viagem (P50) e o percentil 85 (P85). Então, para cada trecho percorrido em cada intervalo de 15 minutos, teve-se como resultado uma coluna informando o tempo mediano e uma coluna informando o tempo do percentil 85 do tempo de viagem no trecho e intervalo.

A etapa da reconstrução da tabela de horários *stop_times.txt* utilizou uma amostra de dados de GPS que foi advinda da etapa de consolidação. Essa amostra já contava com a exclusão de algumas linhas integralmente (principalmente linhas complementares) e outras parcialmente. Na agregação descrita acima, 17% dos trechos e intervalos tiveram uma amostra menor que 10 observações de tempo de viagem, e foram deletadas. Essas duas situações de descarte de amostra tendem a ter um viés, visto que ocorrem em locais periféricos de menor frequência. Para esses casos (trechos) onde não foi possível estimar o tempo de viagem, foi utilizado o valor programado do GTFS. Isso pode ser identificado como a principal limitação nessa etapa do trabalho. 

Os três últimos objetivos buscavam comprovar a importância do método estabelecido, e para isso foram testadas três hipóteses para acessibilidade por transporte público: 1) há diferença entre a acessibilidade estimada pelo GTFS Programado em relação ao GTFS Corrigido (P50); 2) há diferença entre a acessibilidade estimada pelos tempos de viagem medianos (P50) e de percentil 85 (P85); 3) há diferença entre a acessibilidade para diferentes tempos de partida de viagem. O método estabelecido anteriormente foi então aplicado para 1 mês de registro de GPS de Fortaleza, com a posterior aplicação de um algoritmo para a estimação do tempo de viagem entre cada par origem-destino para cada GTFS produzido e para 5 horários de partida em hora pico (05:45, 06:00, 06:15, 06:30 e 06:45).

Essas hipóteses foram então testadas para acessibilidade para trabalho e educação com o uso de um indicador cumulativo de oportunidades. Foi proposta a utilização dos dados de bilhetagem para a estimação do tempo limite a ser utilizados nos indicadores. A partir desses dados foram estimadas as origens e destinos das viagens por motivo trabalho (viagens feitas com vale transporte) e por motivo educação (viagens feitas com carteira de estudante). Utilizando a mediana dos tempos de viagem calculados entre pares-origem destino do OTP, foi então calculada a distribuição dos tempos de viagem realizados para viagens por vale transporte e carteira de estudante. Por fim, os percentis 75 desses tempos foram utilizados para definir os tempos limites, resultando em 65 minutos para trabalho e 50 minutos para educação. Os indicadores de acessibilidade foram então estimados.

Foi encontrado que, para a hipótese 1, a acessibilidade estimada para trabalho com o uso do GTFS Programado superestima a acessibilidade na maioria das agregações espaciais, com uma mediana da diferença de acessibilidade relativa entre os cenários de 3,5%. Em certas áreas, a diferença absoluta pode chegar a mais de 100 mil empregos superestimados (caso fosse usado o GTFS Programado). Para as atividades de educação, por conta do diferente padrão de distribuição dessas oportunidades na cidade, a dispersão da diferença relativa tende a ser menor, com uma mediana de 3% para a subestimação com o uso do GTFS Programado.

Para a hipótese 2, primeiramente foi observado visualmente que há uma diferença de acessibilidade para empregos entre os cenários P50 e P85. Em seguida, foi mapeado a diferença absoluta de acessibilidade que a imprevisibilidade do sistema pode causar: há uma aglomeração de hexágonos que possui diferenças de até 200 mil empregos acessíveis para os cenários diferentes. Foi mostrado como isso acontece a partir da análise de uma agregação individualmente, mostrando que essa grande diferença de acesso absoluto acontece porque o sistema de transportes mais carregado (P85) leva o usuário a deixar de acessar as principais zonas de empregos da cidade (dentro do tempo limite de 65 minutos).

Por fim, a hipótese 3 foi testada através do cálculo do coeficiente de variação da acessibilidade para empregos e educação para os horários de partida (n = 5 para hora pico). Foi mostrado que a variação tende a aumentar quando se distancia dos corredores de ônibus e de zonas de alta frequência de serviço. Isso indica que a frequência tem um papel importante na acessibilidade, diminuindo consideravelmente o tempo de espera dos usuários.

Os resultados encontrados mostram a importância que os horários empíricos e sua dispersão tem na variabilidade da acessibilidade quando a distribuição de diferentes atividades são levadas em consideração. As atividades de trabalho são mais concentradas no centro da cidade, o que ocasiona um grande fluxo no sentido periferia-centro, que leva a altos e imprevisíveis tempos de viagens por transporte público. Assim, os veículos têm uma pontualidade menor (causando os resultados mostrados na hipótese 1) e uma variabilidade no tempo de viagem maior (causando os resultados mostrados na hipótese 2). Quando as atividades de educação são consideradas, acontece uma inversão no cenário. Essas atividades, menos concentradas na região central, assumem fluxos de acesso em sentidos opostos ao do pico trabalho da manhã, resultando em vias de acesso menos congestionadas e mais previsíveis. Isso é refletido na avaliação da hipótese 2 para essa atividade: a maior pontualidade dos veículos leva a uma menor variação entre os cenários. 

A análise das hipóteses finalizou com a demonstração de como as variações encontradas na acessibilidade podem impactar os tomadores de decisões em avaliações de intervenções de transporte. Foi argumentado que o uso de horários programados ou o uso de horários empíricos medianos podem levar à superestimação de intervenções baseadas em métricas de acessibilidade. Indo adiante, a utilização desses dados também pode levar a decisões equivocadas de intervenções, optando por alternativas que não levem em consideração a falta de previsibilidade do sistema.  

Espera-se que estudos futuros que utilizem dados de GTFS para estimar acessibilidade busquem incorporar dados empíricas de tempo de viagem a partir do rastreamento da frota, seja para melhorar a qualidade da estimação ou para estudar a variabilidade (tanto de tempo de viagem como de tempo de partida). Senão, que pelo menos reconheçam as limitações que a utilização de um GTFS Programado impõe. 

O método foi proposto pensando na sua replicação para diferentes realidades. Entretanto, algumas considerações precisam ser feitas sobre como esse método pode ser utilizado para outros conjuntos de dados.


## Sobre a reprodutibilidade do método


O método desenvolvido neste trabalho contou com bases de dados de GPS, bilhetagem, GTFS e cadastro dos usuários do sistema de transporte público de Fortaleza. Os dados continham alguns inconsistências e informações faltantes, então primeiramente foi necessário consolidá-los e integrá-los.

O método proposto no capítulo 4, então, parte de dados consolidados de transporte público, e o seu funcionamento para dados de outras cidades depende disso. É sabido, entretanto, que enquanto dados de GTFS são dados padronizados (e métodos utilizados neste trabalho devem funcionar para qualquer outra caso), dados de bilhetagem e GPS podem variar significativamente.

Uma das diferenças na metodologia desta dissertação diz respeito ao uso de dados arquivados de GPS. Dados arquivados de GPS tendem a ser mais problemáticos, imperfeitos, e com informações faltantes. Isso foi mostrado, por exemplo, no trabalho de @Arbex2016 para os dados de São Paulo e através de uma rápido análise dos dados de GPS do Rio de Janeiro, Brasil. Essa amostra de situações, mesmo pequena, levou a crer que dados arquivados de outras cidades do Brasil ou do mundo sigam o mesmo padrão de qualidade.

Portanto, do lado dos dados de GPS, o método é inteiramente reproduzível caso o dado tenha informações básicas como a linha, hora, veículo e localização. Caso o dado já tenha informação do sentido da viagem, é necessário pular essa etapa na metodologia e seguir adiante para as demais etapas de estimação do momento de passagem em cada parada, etc.

Com os dados de GPS checados, é importante também ressaltar a importância de dados confiáveis de GTFS. No método desenvolvido, a integração das bases requer que a grande maioria das linhas estejam operando de acordo com o previsto no GTFS, ou seja, que estejam respeitando o itinerário, que sigam a devida ordem de paradas e que terminem e comecem suas viagens nos pontos previstos. Qualquer descompasso em relação a essa integração pode levar com que a estimação dos tempos de viagem naquela linha sejam parcialmente/totalmente descartados. Devido ao bom trabalho realizado pela ETUFOR, os dados de GTFS apresentavam uma boa conformidade com o que era executado, resultando num grande aproveitamento da amostra. É entendido, entretanto, que outros dados de GTFS não tenham o mesmo padrão de qualidade, e/ou que o sistema na realidade não siga o planejado.

Ainda em relação aos dados de GTFS, neste trabalho foram adotadas duas premissas para a correção: a primeira viagem de cada veículo é correta e a oferta programada (quantidade de veículos) das linhas é correta. Por meio de conversas e apresentação de dados por parte do gestores foi possível concluir que essas premissas são factíveis. Porém, entende-se que essa não é a realidade para outras cidades. Nesse caso, recomenda-se que a tabela *stop_times* do GTFS seja recomposta exatamente com a oferta observada de um dia ou mais nos arquivos de GPS (como foi feito por @Wessel2017). Evidente que para isso é necessário que o dado de GPS compreenda todas as viagens realizadas no sistema (que não foi o caso do SIT-FOR).

Os dados de GTFS de Fortaleza são do tipo *stop_times*, que contam com uma tabela de horários do transporte público. Outro tipo de GTFS, baseado em um arquivo *frequency*, são ainda mais aproximados e sujeitos a erros que os anteriores. O arquivo *frequency* apresenta informações de frequência programada da linha (headway previsto), e os tempos de viagem entre as paradas das linhas são considerados os mesmo para todos os horários. Nesse caso, é necessário construir completamente o arquivo *stop_times*, não somente reconstruir. Assim, a contribuição dos dados de GPS é maior ainda.

Espera-se também que os códigos disponibilizados no Github sirvam para facilitar a reprodutibilidade do método. É necessário algum conhecimento na linguagem de programação R para poder adaptar diferentes casos para o código desenvolvido para Fortaleza, mas entende-se que uma pessoa com um conhecimento intermediário seja capaz de reproduzi-lo. 

## Qualidade e disponibilidade de dados de transporte público

O principal problema dessa pesquisa diz respeito à integração das diversas bases de transporte público. Como foi visto na etapa de consolidação, as duas principais bases (bilhetagem e GPS) apresentavam identificadores únicos de veículo com numerações diferentes. Para localizar as validações ou para estimar a linha do GPS, é necessário que esses números tenham correspondência. Existe uma base que permite fazer essa integração, mas que acaba deixando muitos veículos de fora. Essa falha na integração faz com que o big data represente agora uma amostra do sistema, e não a mais a população diária tanto dos dados da demanda como dos dados da oferta. E uma amostra, claro, sempre trás consigo um viés, que não foi analisado neste trabalho.

Passada a primeira etapa na integração, a segunda etapa também traz alguns problemas: há algumas linhas faltantes na base de GTFS. Algumas operações como estimar corretamente a parada de embarque dos usuário ou filtrar espacialmente registros de GPS de uma linha não são possíveis caso a linha em questão não exista na base do GTFS. Há outras formas de contornar isso, mas que também trazem consigo muita imprecisão. Tendo em vista o restante do método, uma linha faltante do GTFS comprometeria uma análise daquela linha de qualquer forma porque não teria como corrigir uma tabela de horários inexistente.

A partir dessas observações, recomenda-se aqui uma maior ação dos responsáveis pelas bases de dados (ETUFOR e M2M) no que diz respeito a sua integração. Bases de dados com identificadores únicos iguais permitiriam inclusive uma maior facilidade na integração para pesquisadores que não sejam muito proficientes em ferramentas de manipulação de dados. 

Apesar dessa problemática, é necessário identificar que a disponibilização e coleta de todos os dados (big data) de transporte público do SIT-FOR não representou um problema para essa pesquisa. Os dados foram disponibilizados numa parceria da Prefeitura de Fortaleza com a Universidade Federal do Ceará, mas a prefeitura também tem um portal de dados abertos de transporte público (http://dados.fortaleza.ce.gov.br/catalogo/organization/etufor), mesmo que desatualizado. Essa não é a realidade para a grande parte das cidades brasileiras. Muitos municípios têm relutância em compartilhar dados de transporte público, especialmente dados de bilhetagem, que podem apresentar informações da demanda, e esse tipo de política acaba comprometendo pesquisas na área

## Recomendações futuras para trabalhos acadêmicos

A aplicação do método de integração dos dados de GPS com GTFS apresentou alguns subprodutos que oferecem oportunidades para trabalhos futuros. Dados de tempo de viagem entre paradas já foram utilizados por @Arbex2016 para fazer análises ex-post da implementação de corredores de ônibus. Para o SIT-FOR, @Rabay2017 já analisou velocidade operacionais entre segmentos constantes de via, mas se reservou a analisar poucas linhas. Recomenda-se, portanto, a utilização desse subproduto para uma análise mais completa da velocidade operacional do sistema.

Outras análises possíveis com uma extensão do método são análises ex-ante do impacto que intervenções no transportes tem na acessibilidade. A alteração de parâmetros e adição de linhas aos arquivos GTFS permitem responder perguntas como: Qual o impacto na acessibilidade do aumento da frequência de uma linha de metrô? Qual o impacto da adição de uma linha de BRT para a acessibilidade da cidade? A integração do GTFS e OTP para a estimação de tempos de viagens entre pares origem-destino permite responder essas perguntas de forma mais ágil e integrada. A utilização dos hexágonos H3 de alta resolução permite visualizar tendências que são invisíveis em outras agregações espaciais. Para o Rio de Janeiro, o trabalho de @Pereira2019 tratou de responder algumas dessas perguntas. Recomendam-se trabalhos com essa temática para o SIT-FOR, principalmente utilizando o método mais detalhado de output do OTP.

A parte de resultados do trabalho teve um foco maior em mostrar a importância do método que foi proposto. São recomendados estudos que se aprofundem na análise da acessibilidade principalmente de duas temáticas levantadas: 1) no impacto do horário de partida na acessibilidade e 2) no impacto da variabilidade da oferta (tempo de viagem) na acessibilidade. Para o primeiro, recomenda-se principalmente aumentar o tamanho da amostra de hora de partida coletados. A amostra coletada aqui foi de 5 momentos de partidas, que é considerado pequena, ainda assim mostrando como a frequência do serviço interfere na acessibilidade. Para o segundo, recomenda-se uma análise mais detalhadas de pontos críticos da cidade que tem sua acessibilidade afetada pela alta variabilidade na oferta do transporte público. Recomenda-se, por fim, estudos que analisem com uma maior precisão estatística as diferenças tanto na acessibilidade por horário de partida como nos cenários de variabilidade. Perguntas que podem ser feitas incluem: os resultados são estatisticamente diferentes? Há um efeito da espacialidade nessas diferenças? Qual o seu tamanho?

Recomenda-se também a replicação do método de integração do GPS e GTFS para dados de outras cidades. O método foi feito pensando em dados arquivados de GPS, mas é possível que existam outros tipos de dados com outras limitações. A tentativa de replicação do método permitirá a adaptação do método para outros dados, aumentando seu alcance.

Outra sugestão de trabalho futuro é a estimação da acessibilidade baseado nas limitações de tempo/espaço de cada usuário de transporte público. Existem métodos consolidados na literatura [@Trepanier2007; @Munizaga2012] que estimam o diário de deslocamento para cada usuário do transporte público (quais deslocamentos foram feitos? Em quais linhas? Quanto tempo levou?), e, junto a dados de gênero e idade desses usuários,  esses diários podem ser utilizados para avaliar a acessibilidade considerando as restrições temporais/sociais/comportamentais impostas a esses grupos. Dessa forma, algumas hipóteses de restrição de acessibilidade podem ser estudadas, como:

* Idosos tendem a caminhar menos e buscar rotas mais seguras que podem levar a tempos de viagem superiores, o que pode diminuir sua acessibilidade;
* Mulheres tendem a fazer mais viagens encadeadas que homens (deixar filhos na escola, fazer compras etc), o que pode diminuir sua acessibilidade às demais atividades;
* Pessoas que gastam muito tempo no deslocamento ao trabalho têm pouco tempo restante para acessar atividades de educação e de lazer.

Alguns desafios para esse tipo de análise podem ser encontrados. O SIT-FOR, no seu sistema tronco-alimentador, apresenta terminais de integração fechados onde os usuários que chegam de ônibus não precisam validar para embarcar em outro ônibus. Isso significa que na base da bilhetagem muitos usuários terão trechos da sua viagem que não serão registrados. Os métodos de estimação do diário de deslocamento dos usuários comumente desenvolvidos não abordam esse tipo de falta de informação. Portanto, é necessário desenvolver (ou adaptar) os métodos existentes para incorporar a realidade do SIT-FOR, podendo assim estimar cada etapa do deslocamento e partir para as análises de acessibilidade.

Além disso, muitas das restrições de acessibilidade à oportunidades enfrentadas por mulheres, por exemplo, podem não ser refletidas no seu diário de deslocamento no transporte público. Pode ser levantada a hipótese, por exemplo, que mulheres tem restrição de acessibilidade porque gastam mais tempos que os homens fazendo viagens encadeadas como levando o filho a pé à escola, por exemplo. Por isso pode ser interessante juntar o diário dos deslocamentos por transporte público com pesquisas domiciliares ou dados do censo que contenham informações pessoais sobre deslocamentos diários.

Este trabalho também esboçou uma discussão sobre o conceito de acessibilidade normativa x acessibilidade positiva proposto por @Paez2012, e propôs uma metodologia e aplicou o conceito positivo com o uso dos dados de bilhetagem. A aplicação buscou estimar o tempo de viagem do percentil 75 para viagens motivo trabalho e educação, partindo da hipótese que o tempo reservado para as atividades era diferente. A hipótese, que foi confirmada, também abre espaço para a estratificação desse conceito tanto para renda, idade, local de residência ou gênero.

Outra potencialidade dos dados de bilhetagem na acessibilidade positiva é na calibração de modelos gravitacionais. O diário detalhado de viagem dos usuários permite o cálculo de uma matriz origem destino dos deslocamentos por transporte público. Essa informação pode subsidiar a estimação de indicadores de acessibilidade potenciais que utilizam o método gravitacional.

## Recomendações futuras para o poder público

Primeiramente, é necessário reconhecer o papel ainda incipiente da acessibilidade no planejamento urbano feito pelo poder público. Enquanto o conceito é consolidado e aplicado em países da Europa e da América do Norte, poucos casos são conhecidos para cidades brasileiras. O planejamento para a acessibilidade é de certa uma forma uma evolução do planejamento da mobilidade, outrora focado na diminuição do tempo de viagem, de congestionamentos etc. O planejamento da acessibilidade parte do entendimento da cidade como um sistema complexo de interação entre o sistema de transportes e uso do solo. A principal recomendação nesse aspecto é que o poder público mude o foco do seu planejamento. 

A utilização de subprodutos do método também pode ser útil para o poder público. Esses dados permitem analisar trechos que têm baixa velocidade operacional, ou que tendem a ter uma grande variabilidade. Isso dá informações precisas de onde são necessárias infraestruturas para a priorização do transporte público, por exemplo.

Os dados consolidados de bilhetagem apresentam a sua localização, e estas podem ser alocadas à parada mais provável de embarque dos usuários. A agregação das validações por paradas pode fornece informações das paradas mais carregadas do sistema, e podem ser avaliadas intervenções que busquem otimizar e tornar mais confortável o uso da infraestrutura. Um exemplo de intervenção pode ser de pegar as paradas mais carregadas do sistema e criar uma infraestrutura diferenciada para pedestres e ciclistas em volta delas, melhorando as condições de first e last mile.

No que diz respeito à acessibilidade, recomenda-se que o setor público olhe principalmente para áreas que apresentaram uma alta variação de acessibilidade em virtude 1) da hora de partida 2) da variabilidade dos tempos de viagem. Essas áreas precisam de intervenções que tanto aumentem a frequência de veículos como diminuam a influência da variabilidade.